blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/23-5-N-GeekDay/23-5-n-geekday.github.io/discussions
    about: æœ‰é—®é¢˜æˆ–æƒ³æ³•ï¼Ÿæ¬¢è¿åˆ°è®¨è®ºåŒºäº¤æµ
